### ISSUE TITLE
"Something went wrong" - Spotify Crashes when using Spicetify

### ISSUE THREAD

**Issue by SpikeNew7774** [spicetify/cli#3243]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 
    Spotify for Windows (64 bit)
    1.2.53.438.g246d60c9
    xpui_2024-12-18_1734520474687_246d60c
    cef_131.3.1+gcb062df+chromium-131.0.6778.109
    Runtime: Chrome
    Build System: Bazel
- Spicetify version: 2.38.6
```

### 📝 Description

When Spicetify is installed, the app just crashes by saying that Something went wrong. I checked the Devtools and found there's some React Error. I would appriciate if this would get fixed soon, because I'm a Spicetify Extension developer myself, and need to make some updates.

### 📸 Screenshots

When using Spicetify.
![image](https://github.com/user-attachments/assets/a2986490-9e18-4e98-8de6-b80de03e63c1)

Without using Spicetify: (It's just basically Spotify)

Console:
![image](https://github.com/user-attachments/assets/31475b21-f4ae-4cba-9833-338984b9a2ee)
![image](https://github.com/user-attachments/assets/70bfbd50-a7df-4b4c-93dd-172c296516ea)
![image](https://github.com/user-attachments/assets/5e41d4e6-600e-47a3-8bb7-84aaafe08371)
![image](https://github.com/user-attachments/assets/d8ce905a-c839-49b1-aa70-89e7b49f9c11)

**Comment by rxri** [comment]
Yes it will happen. Multiple reloads will help in this instance. There’s no known fix for it and I don’t think there’ll be in v2. I recommend downgrading to `1.2.52` if reloading multiple times on startup is bothering you.

**Comment by SpikeNew7774** [comment]
@rxri Thanks. I actually just downgraded the version and it works now. Thanks!

**Comment by rxri** [comment]
but spicetify besides this works just fine on 1.2.53, so after reloads it will work until you start spotify again

**Comment by SpikeNew7774** [comment]
@rxri Also thanks for the fast response, beacuse my extension is about to have a big update, that I'm finishing up, and I wanted to let the Spicetify team know about this issue.

**Comment by rxri** [comment]
Technically as a fix we could wait until ScrollableContainer is available but when they change something it will be in constant loop, also it would require checking the webpack object over and over

**Comment by AnonymousGryffindor** [comment]
> @rxri Thanks. I actually just downgraded the version and it works now. Thanks!

How do I downgrade?

**Comment by AV3RG** [comment]
Saw someone people referring [this](https://spotify.en.uptodown.com/windows/download/1039951062), not sure if the source can be trusted or not

**Comment by rxri** [comment]
> > > @rxri Thanks. I actually just downgraded the version and it works now. Thanks!
> > 
> > 
> > How do I downgrade?
> 
> Saw someone people referring [this](https://spotify.en.uptodown.com/windows/download/1039951062), not sure if the source can be trusted or not

Use this https://docs.google.com/spreadsheets/d/1wztO1L4zvNykBRw7X4jxP8pvo11oQjT0O5DvZ_-S4Ok and only this

**Comment by levanter4419** [comment]
I downloaded the necessary file to downgrade for Mac but then what? I'm so lost.

**Comment by rxri** [comment]
Inside the .tgz you will have folder that you need to replace with old one in `Spotify.app` (which is a folder) - you may click `Show contents of app` or something in the dropdown

**Comment by rxri** [comment]
Fixed with https://github.com/spicetify/cli/releases/tag/v2.38.7

**Comment by Starra** [comment]
I'm still having the same issue with v2.38.7. I've tried uninstalling and reinstalling Spicetify but that doesn't work.

**Comment by asleepa** [comment]
> Fixed with https://github.com/spicetify/cli/releases/tag/v2.38.7

I am still having this issue despite reinstalling Spicetify, no matter how many times I reload the page.
